### PR TITLE
Bug fix and minor refactoring

### PR DESCRIPTION
**Pull request by vickz84259**
I renamed variables that were vague and also removed an unnecessary empty constructor.

This request also includes a fix to the withdrawal issue. This was where a user could have withdrawn beyond his or her limit.

### CODE REVIEW

**Comment by vickz84259** [comment]
I added another commit to the original pull request (#2).

This commit removes unnecessary getters and setters.

**Comment by vickz84259** [comment]
In the upcoming commits I'll be doing last touches on the Bank and Client Classes before heading for the problematic Records class.

**Comment by vickz84259** [comment]
Implementation of the ability to read user data from a file. Checkout the commit message for 5a8d2e2 for more details on how it works.

I'll finish up on how to create the file since now you have to create  it manually. Once that's done, the ball is in your court to implement features like: users creating passwords when registering, requiring the password/pin to access an account and so many more features.

**Comment by vickz84259** [comment]
Comment on any commit you need help understanding what was happening. 

Cheers.

**Comment by eric-mahasi** [comment]
Thanks so much for all the assistance. I truly appreciate your effort. This project has shown me that dev work is so much easier with collaboration like this. I hope that this only leads to bigger projects in the future

**Pull request merged**
